# Generated by Django 5.0.4 on 2024-04-23 06:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hailmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HailEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('size', models.FloatField()),
                ('date_time_event', models.DateTimeField()),
                ('date_time_updated', models.DateTimeField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hail Events',
            },
        ),
    ]
