# Generated by Django 5.0.4 on 2024-04-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hailmaps', '0002_hailevents'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hailevents',
            unique_together={('location', 'size', 'date_time_event')},
        ),
    ]
