# Generated by Django 5.0.4 on 2024-04-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hailmaps', '0005_hailmapsdatasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='hailmapsdatasource',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
